apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - route.yaml
  - rolebinding.yaml

configMapGenerator:
  - name: skillctl-catalog-config
    literals:
      - registry-url=image-registry.openshift-image-registry.svc:5000

patches:
  - path: deployment-patch.yaml
